USE [master]
GO
/****** Object:  Database [ISSUES_TRACKING]    Script Date: 11/12/2025 9:29:33 AM ******/
CREATE DATABASE [ISSUES_TRACKING]
GO
ALTER DATABASE [ISSUES_TRACKING] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ISSUES_TRACKING].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ISSUES_TRACKING] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ARITHABORT OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ISSUES_TRACKING] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ISSUES_TRACKING] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ISSUES_TRACKING] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ISSUES_TRACKING] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET RECOVERY FULL 
GO
ALTER DATABASE [ISSUES_TRACKING] SET  MULTI_USER 
GO
ALTER DATABASE [ISSUES_TRACKING] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ISSUES_TRACKING] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ISSUES_TRACKING] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ISSUES_TRACKING] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ISSUES_TRACKING] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ISSUES_TRACKING] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ISSUES_TRACKING', N'ON'
GO
ALTER DATABASE [ISSUES_TRACKING] SET QUERY_STORE = OFF
GO
USE [ISSUES_TRACKING]
GO
/****** Object:  Table [dbo].[ISSUE]    Script Date: 11/12/2025 9:29:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ISSUE](
	[ID_ISSUE] [int] IDENTITY(1,1) NOT NULL,
	[TITLE] [nvarchar](100) NOT NULL,
	[DESCRIPTION_ISSUE] [nvarchar](500) NOT NULL,
	[ID_STATUS_ISSUE] [int] NOT NULL,
	[ID_PRIORITY_ISSUE] [int] NOT NULL,
	[CREATE_USER] [nvarchar](50) NULL,
	[CREATE_DATE] [datetime] NULL,
	[RESOLVE_USER] [nvarchar](50) NULL,
	[RESOLVE_DATE] [datetime] NULL,
 CONSTRAINT [PK_ISSUE] PRIMARY KEY CLUSTERED 
(
	[ID_ISSUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PRIORITY_ISSUE]    Script Date: 11/12/2025 9:29:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRIORITY_ISSUE](
	[ID_PRIORITY_ISSUE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION_PRIORITY] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_PRIORITY_ISSUE] PRIMARY KEY CLUSTERED 
(
	[ID_PRIORITY_ISSUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[STATUS_ISSUE]    Script Date: 11/12/2025 9:29:33 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[STATUS_ISSUE](
	[ID_STATUS_ISSUE] [int] IDENTITY(1,1) NOT NULL,
	[DESCRIPTION_STATUS] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_STATUS_ISSUE] PRIMARY KEY CLUSTERED 
(
	[ID_STATUS_ISSUE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[ISSUE] ON 
GO
INSERT [dbo].[ISSUE] ([ID_ISSUE], [TITLE], [DESCRIPTION_ISSUE], [ID_STATUS_ISSUE], [ID_PRIORITY_ISSUE], [CREATE_USER], [CREATE_DATE], [RESOLVE_USER], [RESOLVE_DATE]) VALUES (1, N'First issue', N'This is a test issue', 1, 2, N'system', CAST(N'2025-11-11T23:38:24.850' AS DateTime), NULL, NULL)
GO
SET IDENTITY_INSERT [dbo].[ISSUE] OFF
GO
SET IDENTITY_INSERT [dbo].[PRIORITY_ISSUE] ON 
GO
INSERT [dbo].[PRIORITY_ISSUE] ([ID_PRIORITY_ISSUE], [DESCRIPTION_PRIORITY]) VALUES (1, N'High')
GO
INSERT [dbo].[PRIORITY_ISSUE] ([ID_PRIORITY_ISSUE], [DESCRIPTION_PRIORITY]) VALUES (2, N'Low')
GO
SET IDENTITY_INSERT [dbo].[PRIORITY_ISSUE] OFF
GO
SET IDENTITY_INSERT [dbo].[STATUS_ISSUE] ON 
GO
INSERT [dbo].[STATUS_ISSUE] ([ID_STATUS_ISSUE], [DESCRIPTION_STATUS]) VALUES (1, N'Open')
GO
INSERT [dbo].[STATUS_ISSUE] ([ID_STATUS_ISSUE], [DESCRIPTION_STATUS]) VALUES (2, N'Resolved')
GO
SET IDENTITY_INSERT [dbo].[STATUS_ISSUE] OFF
GO
ALTER TABLE [dbo].[ISSUE]  WITH CHECK ADD  CONSTRAINT [FK_PRIORITY_ISSUE] FOREIGN KEY([ID_PRIORITY_ISSUE])
REFERENCES [dbo].[PRIORITY_ISSUE] ([ID_PRIORITY_ISSUE])
GO
ALTER TABLE [dbo].[ISSUE] CHECK CONSTRAINT [FK_PRIORITY_ISSUE]
GO
ALTER TABLE [dbo].[ISSUE]  WITH CHECK ADD  CONSTRAINT [FK_STATUS_ISSUE] FOREIGN KEY([ID_STATUS_ISSUE])
REFERENCES [dbo].[STATUS_ISSUE] ([ID_STATUS_ISSUE])
GO
ALTER TABLE [dbo].[ISSUE] CHECK CONSTRAINT [FK_STATUS_ISSUE]
GO
USE [master]
GO
ALTER DATABASE [ISSUES_TRACKING] SET  READ_WRITE 
GO
